# Generated by Django 5.1.7 on 2025-03-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
