# Generated by Django 5.1.7 on 2025-03-30 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
